<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../OrderCreation/OrderCreation.csproj" />
    <ProjectReference Include="..\..\Olimpi Framework\Olimpi Framework.csproj" />
    <ProjectReference Include="..\CAlgoInterface\CAlgoInterface.csproj" />
  </ItemGroup>

</Project>
